### ISSUE TITLE
The blending of the camera image with the semantics data is crashing

### ISSUE THREAD

**Issue by MrCsabaToth** [TreeWalks/tree-walk-guide#10]
Needs to be debugged ASAP

**Comment by MrCsabaToth** [comment]
```
E/BLASTBufferQueue: BLASTBufferItemConsumer::onDisconnect()
E/AndroidRuntime: FATAL EXCEPTION: GLThread 3401
    Process: dev.csaba.armap.treewalk, PID: 25755
    java.lang.AssertionError: Assertion failed
        at dev.csaba.armap.treewalk.helpers.ImageUtilsKt.imageToBitmap(ImageUtils.kt:14)
        at dev.csaba.armap.treewalk.TreeWalkGeoRenderer.getSemanticsBlendedFrame(TreeWalkGeoRenderer.kt:546)
        at dev.csaba.armap.treewalk.TreeWalkGeoRenderer.onDrawFrame(TreeWalkGeoRenderer.kt:198)
        at dev.csaba.armap.common.samplerender.SampleRender$1.onDrawFrame(SampleRender.java:64)
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1593)
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1272)
```

**Comment by MrCsabaToth** [comment]
https://github.com/crow-misia/libyuv-android/blob/main/sample/src/main/java/app/MainActivity.kt
https://stackoverflow.com/questions/28944864/integrating-libyuv-to-my-android-studio-project/75219506#75219506
https://github.com/android/camera-samples/blob/main/CameraUtils/lib/src/main/java/com/example/android/camera/utils/YuvToRgbConverter.kt

**Comment by MrCsabaToth** [comment]
https://stackoverflow.com/questions/75227966/how-to-rotate-and-a-bitmap-or-media-image-from-landscape-to-portrait-w-x-h-h
https://stackoverflow.com/questions/75227417/how-to-obtain-screen-aspect-ratio-unaugmented-camera-image-in-an-arcore-applicat

**Comment by MrCsabaToth** [comment]
Version 2 (1.2) released with the rehauled feature
