### ISSUE TITLE
Helper arrow and watering can crashes

### ISSUE THREAD

**Issue by MrCsabaToth** [TreeWalks/tree-walk-guide#5]
These two object are not anchored to a GPS or even to a position in the AR Scene. Currently I constantly recreating them, maybe that's what causes it? Possibly I need to go low level and not even create an Anchor but a lower level non anchored object somehow?

```
E/BLASTBufferQueue: BLASTBufferItemConsumer::onDisconnect()
E/AndroidRuntime: FATAL EXCEPTION: GLThread 3272
    Process: dev.csaba.armap.treewalk, PID: 4691
    com.google.ar.core.exceptions.FatalException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at com.google.ar.core.Session.throwExceptionFromArStatus(Session.java:14)
        at com.google.ar.core.Session.nativeCreateAnchor(Native Method)
        at com.google.ar.core.Session.createAnchor(Session.java:1)
        at dev.csaba.armap.treewalk.TreeWalkGeoRenderer.onDrawFrame(TreeWalkGeoRenderer.kt:228)
        at dev.csaba.armap.common.samplerender.SampleRender$1.onDrawFrame(SampleRender.java:64)
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1593)
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1272)
```

**Comment by MrCsabaToth** [comment]
This UX is disabled for now. For watering can we can use maybe an overlay of a POV 2D projected 3D watering can (a.k.a. 3D pre-render - not burdening the 3D engine). For the arrows I'll think about it. Even in  AR examples with directional arrows the arrows anchored to a place. We'd need non anchored 3D objects! So we should probably just forget about anchors and wing it by ourselves.
